[workspace]
members = [
  "rkubectl",
  "api_server",
  "rkubelet",
  "resources",
  "controllers",
  "scheduler",
  "rkube_proxy",
]

[patch.crates-io]
bollard = {git = 'https://hub.fastgit.xyz/y-young/bollard'}
