version: "3"

services:
  api_server:
    image: minik8s.xyz/api_server:latest
    container_name: api_server
    ports:
      - "8080:8080"
    environment:
      - "ETCD_ENDPOINT=${ETCD_ENDPOINT}"
      - "METRICS_SERVER=prometheus:9090"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  endpoints-controller:
    image: minik8s.xyz/endpoints-controller:latest
    container_name: endpoints-controller
    environment:
      - API_SERVER_ENDPOINT=http://api_server:8080

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "${FLANNEL_SUBNET}"
